In [1]:
import numpy as np

In [2]:
arr=np.arange(1,10).reshape(3,3)

In [3]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(arr[1:,:1])

[[4]
 [7]]


In [5]:
arr[:1]=1

In [6]:
print(arr)

[[1 1 1]
 [4 5 6]
 [7 8 9]]


In [7]:
arr[:,2]=3

In [8]:
arr

array([[1, 1, 3],
       [4, 5, 3],
       [7, 8, 3]])

In [9]:
arr+arr

array([[ 2,  2,  6],
       [ 8, 10,  6],
       [14, 16,  6]])

In [10]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
arr*arr

array([[ 1,  1,  9],
       [16, 25,  9],
       [49, 64,  9]])

In [12]:
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr**4

array([[   1,    1,   81],
       [ 256,  625,   81],
       [2401, 4096,   81]], dtype=int32)

In [14]:
np.min(arr)

1

In [15]:
np.max(arr)

8

In [16]:
np.mean(arr)

3.888888888888889

In [17]:
np.sqrt(arr)

array([[1.        , 1.        , 1.73205081],
       [2.        , 2.23606798, 1.73205081],
       [2.64575131, 2.82842712, 1.73205081]])

In [18]:
np.mean(arr)

3.888888888888889

In [19]:
np.log(arr)

array([[0.        , 0.        , 1.09861229],
       [1.38629436, 1.60943791, 1.09861229],
       [1.94591015, 2.07944154, 1.09861229]])

In [20]:
np.exp(arr)

array([[2.71828183e+00, 2.71828183e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 2.00855369e+01],
       [1.09663316e+03, 2.98095799e+03, 2.00855369e+01]])

In [21]:
np.sin(arr)

array([[ 0.84147098,  0.84147098,  0.14112001],
       [-0.7568025 , -0.95892427,  0.14112001],
       [ 0.6569866 ,  0.98935825,  0.14112001]])