In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
narr=arr.reshape(3,3)

In [5]:
narr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
tarr=np.array([[13,4,18],[14,1,22],[17,10,27]])

In [7]:
tarr

array([[13,  4, 18],
       [14,  1, 22],
       [17, 10, 27]])

In [8]:
tarr.shape

(3, 3)

In [9]:
tarr.reshape(9,)

array([13,  4, 18, 14,  1, 22, 17, 10, 27])

In [10]:
r1=np.random.rand()

In [11]:
r1

0.5227938206009988

In [12]:
r2=np.random.rand(10)

In [13]:
r2

array([0.09522625, 0.44701775, 0.62646541, 0.77872291, 0.11921017,
       0.78590954, 0.75858926, 0.47238642, 0.12278304, 0.52117954])

In [29]:
r3=np.random.rand(1,2)

In [30]:
r3

array([[0.28528438, 0.50705604]])

In [16]:
r4=np.random.randn(5,2)

In [17]:
r4

array([[-0.66571072, -0.52530437],
       [-1.39303932,  0.60823837],
       [ 1.06045483, -0.21757495],
       [ 0.39379038,  0.89504415],
       [ 1.96028956,  0.22072091]])

In [18]:
r4=np.random.randint(5,500,10)
r4

array([121, 148, 334, 265, 352, 283, 140, 471, 143, 465])

In [19]:
r4.max()

471

In [20]:
r4.argmax()

7

In [21]:
r4.min()

121

In [22]:
r4.argmin()

0

In [23]:
r5=np.linspace(5,50,9)
r5

array([ 5.   , 10.625, 16.25 , 21.875, 27.5  , 33.125, 38.75 , 44.375,
       50.   ])

In [24]:
r6=np.arange(15,5,-2)
r6

array([15, 13, 11,  9,  7])

In [25]:
arr[5:1:-1]

array([6, 5, 4, 3])

In [26]:
carr=arr.copy()
print(carr)

[1 2 3 4 5 6 7 8 9]
