In [1]:
import numpy as np

In [2]:
arr=np.arange(11)

In [3]:
out=np.where(arr%2!=0,arr+1,arr)
print(out)

[ 0  2  2  4  4  6  6  8  8 10 10]


In [4]:
l=[]
n=int(input("Enter number of elements:"))

Enter number of elements:5


In [5]:
print("Enter the elements:")
for i in range(n):
    l.append(int(input(f"Element {i+1}:")))

Enter the elements:
Element 1:3
Element 2:5
Element 3:7
Element 4:9
Element 5:11


In [6]:
arr=np.array(l)

In [7]:
l

[3, 5, 7, 9, 11]

In [8]:
b=[1,3,5,7,9,4,11]

In [9]:
l2=np.array(b)

In [10]:
l2

array([ 1,  3,  5,  7,  9,  4, 11])

In [11]:
np.intersect1d(l,l2)

array([ 3,  5,  7,  9, 11])

In [12]:
b=np.where(arr>4,3,arr)

In [13]:
b

array([3, 3, 3, 3, 3])